#!/bin/bash

# Extract name, type, height, and weight from pokemon.json
name=$(jq -r '.name' pokemon.json | awk '{print toupper(substr($0,1,1)) substr($0,2)}')
type=$(jq -r '.types[0].type.name' pokemon.json | awk '{print toupper(substr($0,1,1)) substr($0,2)}')
weight=$(jq -r '.weight' pokemon.json | awk '{printf "%d", $1/10}')
height=$(jq -r '.height' pokemon.json | awk '{printf "%.1f", $1/10}')

# Output in the exact required format
echo "$name is of type $type, weighs ${weight}kg, and is ${height}m tall."

