#!/bin/bash

# Extract data from pokemon.json
jq -r '.name + " " + (.types[0].type.name) + " " + (.weight|tostring) + " " + (.height|tostring)' pokemon.json |
awk '{
    # Capitalize first letters
    name=toupper(substr($1,1,1)) substr($1,2)
    type=toupper(substr($2,1,1)) substr($2,2)
    # Convert weight to kg (hectograms / 10)
    weight=int($3/10)
    # Convert height to meters (decimeters / 10, 1 decimal)
    height=$4/10
    printf "%s is of type %s, weighs %dkg, and is %.1fm tall.\n", name, type, weight, height
}' |
sed 's/ //g'  # Example use of sed (can adjust to remove extra spaces if needed)

